### ISSUE TITLE
SLASH - Top 50 fandoms: should we combine/consolidate?

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/fanfic#9]

**Comment by jadiehm** [comment]
Example: Star Wars is at 15, 26, and 35. There are some more duplicates as well.

**Comment by jadiehm** [comment]
Lulu feedback: "Also I'm pretty sure Stranger Things, Dragon Age, Genshin Impact, Undertale and The Untamed all fall into one of the genres listed." Should we revisit these genres?

**Comment by jadiehm** [comment]
Alvin feedback: "I’m having a little trouble with color here and clearly figuring out where on the red-blue spectrum some of the purples are. (I think it’s because blue is what you’re highlighting, but the background is also blue?)"

This can't go from red to either green because of color blindness issues. Thinking maybe we break the color rules here and go with the highlighter green for more impact.

**Comment by ashley-cai** [comment]
Agree on the highlighter green -- but that would mean we use black text and another light color for the other side of the spectrum. We can't use pink/green bc accessibility so perhaps a light blue? (sorry to add another color to the scheme, but seems like a fair solution here.)

I also should have been using the fandom collapsed data instead of just fandom -- that has been corrected! I think also to address the dragon age/undertale ones, which I originally categorized under video game, it would be good to just add another highlight category to accomodate them.

I mocked both up in the figma and updated the data in the sheet!

**Comment by jadiehm** [comment]
@ashley-cai 

I think the light blue is ok! Still in the same family. I swap the scales though so that women are highlighter because it stands out more against all the blue. It should be updated in the staging link now.

For the data, we'll also need to update the men/women/non-binary stats for 9 more fandoms. I've [highlighted them in yellow here](https://docs.google.com/spreadsheets/d/14JoMMgrOwwHKvPciLfBFgVEFFdvNYqPDuVn-PnTR2D4/edit?gid=1460397042#gid=1460397042). We could also chose to drop this down to Top 20, which would mean only updating DC and ShadowHunters.

**Comment by ashley-cai** [comment]
Added data for those sections!

**Comment by jadiehm** [comment]
Appreciate it! Just updated!
